# styles.py
import streamlit as st

def injetar_animacao_global():
    st.markdown("""<style>@keyframes fadeInSuave { 0% { opacity: 0; transform: translateY(15px); } 100% { opacity: 1; transform: translateY(0); } } .block-container { animation: fadeInSuave 0.8s ease-out !important; }</style>""", unsafe_allow_html=True)

def injetar_css_login():
    st.markdown("""<style>header {background: rgba(0,0,0,0) !important;} .stDeployButton {display:none;} [data-testid="stForm"] { background-color: #1e1e1e !important; padding: 40px !important; border-radius: 16px !important; box-shadow: 0 15px 40px rgba(0,0,0,0.5) !important; border: 1px solid rgba(255,255,255,0.05) !important; margin-top: 10vh !important; } [data-testid="stForm"] div[data-baseweb="input"] { background-color: #2b2b2b !important; border: 1px solid #444 !important; border-radius: 8px !important; } [data-testid="stForm"] div[data-baseweb="input"]:focus-within { border-color: #4fc3f7 !important; box-shadow: 0 0 10px rgba(79, 195, 247, 0.3) !important; } [data-testid="stForm"] div[data-testid="stTextInput"] input { color: white !important; background-color: transparent !important; padding: 12px !important; outline: none !important; border: none !important; box-shadow: none !important; } [data-testid="InputInstructions"] { display: none !important; }</style>""", unsafe_allow_html=True)

def injetar_css_global():
    st.markdown("""<style>header {background: rgba(0,0,0,0) !important;} .stDeployButton {display:none;} [data-testid="InputInstructions"] { display: none !important; } .stButton > button[kind="primary"] { background-color: #4fc3f7 !important; color: #0e1117 !important; border: none !important; font-weight: bold !important; border-radius: 8px !important; transition: all 0.2s !important; } .stButton > button[kind="primary"]:hover { background-color: white !important; box-shadow: 0 0 15px rgba(255, 255, 255, 0.8) !important; transform: scale(1.02) !important; } .pallet-box { position: relative; overflow: visible; transition: transform 0.2s, box-shadow 0.2s; cursor: pointer; } .pallet-box:hover { transform: translateY(-5px); box-shadow: 0 10px 15px rgba(0,0,0,0.3) !important; z-index: 50; } .fefo-tooltip { display: none; position: absolute; bottom: 110%; left: 50%; transform: translateX(-50%); background-color: rgba(18, 18, 18, 0.98); color: #fff; padding: 20px; border-radius: 12px; width: 320px; flex-direction: column; justify-content: center; align-items: flex-start; z-index: 100; box-shadow: 0 10px 30px rgba(0,0,0,0.8); border: 1px solid rgba(255,255,255,0.15);} .pallet-box:hover .fefo-tooltip { display: flex !important; } .mini-pallet { width: 60px; height: 60px; border-radius: 6px; position: relative; cursor: pointer; border: 1px solid rgba(255,255,255,0.2); } .mini-pallet:hover { border: 2px solid white; transform: scale(1.15); z-index: 50; } .mini-pallet .fefo-tooltip { bottom: 120%; } .mini-pallet:hover .fefo-tooltip { display: flex !important; } </style>""", unsafe_allow_html=True)